# The number of plots in your map
game_size: 8

# The coordinates of each plot (the center of the plot)
plot_0: 185,5,155
plot_1: 185,5,112
plot_2: 143,5,112
plot_3: 143,5,155
plot_4: 101,5,112
plot_5: 60,5,112
plot_6: 60,5,70
plot_7: 101,5,70

# How wide a plot is. The player won't be able to build further than plot_size blocks from the center of the plot
plot_size: 25

# How far up and down can the player go in his plot
plot_up: 20
plot_down: 1

# Set to false if you're not me
database_enabled: false
proxy_enabled: false

# Settings for the database
database_address: 127.0.0.1
database_name: Cookie
database_user: Cookie
database_password: Cookie

# List all themes separated by ","
themes: Farm, Summer, Camping, Volcano, Guns, House, Candle, Rabbit, Pizza, Car, Emoji, Smartphone, Candies, Birds, Skyscraper, McDonald's, Desk, Fast Food, Food, Dragon, Snowman, Restaurant, Tank, Nintendo, Mario, Clock, BasketBall, Ice Cream, Shop, Shoes, Bag,, Maze, Magic, Winter, Soccer, Airpane, Pokemon, Minions, TV, Lighthouse, Console, Simpsons, Wizard, Halloween, Skeleton, Free Style!, Pixel Art, Science, Animals, Candies, Alien, Sponge Bob, Rocket, Pyramid, Upside Down, Train, Ruins