# The number of plots in your map
game_size: 8

# The coordinates of each plot (the center of the plot)
plot_1: 184,20,156
plot_2: 184,20,114
plot_3: 142,20,114
plot_4: 142,20,156
plot_5: 100,20,114
plot_6: 56,20,114
plot_7: 56,20,72
plot_8: 100,20,72

# How wide a plot is. The player won't be able to build further than plot_size blocks from the center of the plot
plot_size: 10

# How far up and down can the player go in his plot
plot_up: 8
plot_down: 2

# Set to false if you're not me
database_enabled: false
proxy_enabled: false

# Settings for the database
database_address: 127.0.0.1
database_name: Cookie
database_user: Cookie
database_password: Cookie

# List all themes separated by ","
themes: Farm, Summer, Camping, Volcano, Guns, House, Candle, Rabbit, Pizza, Car, Emoji, Smartphone, Candies, Birds, Skyscraper, McDonald's, Desk, Fast Food, Food, Dragon, Snowman, Restaurant, Tank, Nintendo, Mario, Clock, BasketBall, Ice Cream, Shop, Shoes, Bag,, Maze, Magic, Winter, Soccer, Airpane, Pokemon, Minions, TV, Lighthouse, Console, Simpsons, Wizard, Halloween, Skeleton, Free Style!, Pixel Art, Science, Animals, Candies, Alien, Sponge Bob, Rocket, Pyramid, Upside Down, Train, Ruins